<?php

namespace Database\Seeders;

use App\Models\Airport;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AirportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $airports = [
            [
                'name' => 'Adana Şakirpaşa Havalimanı',
                'code' => 'LTAF',
                'latitude' => '36.982222',
                'longitude' => '35.281944',
                'country_id' => 1,
            ],
            [
                'name' => 'Ankara Esenboğa Havalimanı',
                'code' => 'LTAC',
                'latitude' => '40.128056',
                'longitude' => '32.995833',
                'country_id' => 1,
            ],
            [
                'name' => 'Antalya Havalimanı',
                'code' => 'LTAI',
                'latitude' => '36.900278',
                'longitude' => '30.792778',
                'country_id' => 1,
            ],
            [
                'name' => 'Alanya Gazipaşa Havalimanı',
                'code' => 'LTFG',
                'latitude' => '36.299167',
                'longitude' => '32.300556',
                'country_id' => 1,
            ],
            [
                'name' => 'Balıkesir Koca Seyit Havalimanı',
                'code' => 'LTFD',
                'latitude' => '39.5525',
                'longitude' => '27.010278',
                'country_id' => 1,
            ],
            [
                'name' => 'Bursa Yenişehir Havalimanı',
                'code' => 'LTBR',
                'latitude' => '40.255833',
                'longitude' => '29.561944',
                'country_id' => 1,
            ],
            [
                'name' => 'Çanakkale Havalimanı',
                'code' => 'LTBH',
                'latitude' => '40.1375',
                'longitude' => '26.430833',
                'country_id' => 1,
            ],
            [
                'name' => 'Denizli Çardak Havalimanı',
                'code' => 'LTAY',
                'latitude' => '37.787778',
                'longitude' => '29.705',
                'country_id' => 1,
            ],
            [
                'name' => 'Diyarbakır Havalimanı',
                'code' => 'LTCC',
                'latitude' => '37.901111',
                'longitude' => '40.201944',
                'country_id' => 1,
            ],
            [
                'name' => 'Elazığ Havalimanı',
                'code' => 'LTCA',
                'latitude' => '38.5975',
                'longitude' => '39.281389',
                'country_id' => 1,
            ],
            [
                'name' => 'Erzurum Havalimanı',
                'code' => 'LTCE',
                'latitude' => '39.955278',
                'longitude' => '41.1075',
                'country_id' => 1,
            ],
            [
                'name' => 'Hasan Polatkan Havalimanı',
                'code' => 'LTBY',
                'latitude' => '39.8125',
                'longitude' => '30.527222',
                'country_id' => 1,
            ],
            [
                'name' => 'Gaziantep Havalimanı',
                'code' => 'LTAJ',
                'latitude' => '36.947778',
                'longitude' => '37.479028',
                'country_id' => 1,
            ],
            [
                'name' => 'Hatay Havalimanı',
                'code' => 'LTDA',
                'latitude' => '36.372222',
                'longitude' => '36.290278',
                'country_id' => 1,
            ],
            [
                'name' => 'Isparta Süleyman Demirel Havalimanı',
                'code' => 'LTFC',
                'latitude' => '37.855833',
                'longitude' => '30.370278',
                'country_id' => 1,
            ],
            [
                'name' => 'İstanbul Havalimanı',
                'code' => 'LTFM',
                'latitude' => '41.260833',
                'longitude' => '28.722222',
                'country_id' => 1,
            ],
            [
                'name' => 'Sabiha Gökçen Havalimanı',
                'code' => 'LTFJ',
                'latitude' => '40.894167',
                'longitude' => '29.309167',
                'country_id' => 1,
            ],
            [
                'name' => 'Adnan Menderes Havalimanı',
                'code' => 'LTBJ',
                'latitude' => '38.289167',
                'longitude' => '27.155',
                'country_id' => 1,
            ],
            [
                'name' => 'Kars Harakani Havalimanı',
                'code' => 'LTCF',
                'latitude' => '40.562222',
                'longitude' => '43.114722',
                'country_id' => 1,
            ],
            [
                'name' => 'Erkilet Havalimanı',
                'code' => 'LTAU',
                'latitude' => '38.770278',
                'longitude' => '35.495278',
                'country_id' => 1,
            ],
            [
                'name' => 'Cengiz Topel Havalimanı',
                'code' => 'LTBQ',
                'latitude' => '40.735',
                'longitude' => '30.083333',
                'country_id' => 1,
            ],
            [
                'name' => 'Konya Havalimanı',
                'code' => 'LTAN',
                'latitude' => '37.980556',
                'longitude' => '32.5625',
                'country_id' => 1,
            ],
            [
                'name' => 'Zafer Havalimanı',
                'code' => 'LTBZ',
                'latitude' => '39.111389',
                'longitude' => '30.13',
                'country_id' => 1,
            ],
            [
                'name' => 'Malatya Havalimanı',
                'code' => 'LTAT',
                'latitude' => '38.432222',
                'longitude' => '38.083056',
                'country_id' => 1,
            ],
            [
                'name' => 'Dalaman Havalimanı',
                'code' => 'LTBS',
                'latitude' => '36.7125',
                'longitude' => '28.792778',
                'country_id' => 1,
            ],
            [
                'name' => 'Milas-Bodrum Havalimanı',
                'code' => 'LTFE',
                'latitude' => '37.249444',
                'longitude' => '27.664722',
                'country_id' => 1,
            ],
            [
                'name' => 'Nevşehir Kapadokya Havalimanı',
                'code' => 'LTAZ',
                'latitude' => '38.775278',
                'longitude' => '34.524444',
                'country_id' => 1,
            ],
            [
                'name' => 'Ordu-Giresun Havalimanı',
                'code' => 'LTCB',
                'latitude' => '40.966944',
                'longitude' => '38.079722',
                'country_id' => 1,
            ],
            [
                'name' => 'Rize-Artvin Havalimanı',
                'code' => 'LTFO',
                'latitude' => '41.168611',
                'longitude' => '40.828889',
                'country_id' => 1,
            ],
            [
                'name' => 'Samsun Çarşamba Havalimanı',
                'code' => 'LTFH',
                'latitude' => '41.265556',
                'longitude' => '36.536944',
                'country_id' => 1,
            ],
            [
                'name' => 'Sinop Havalimanı',
                'code' => 'LTCM',
                'latitude' => '42.015833',
                'longitude' => '35.066389',
                'country_id' => 1,
            ],
            [
                'name' => 'Sivas Nuri Demirağ Havalimanı',
                'code' => 'LTAR',
                'latitude' => '39.814167',
                'longitude' => '36.9025',
                'country_id' => 1,
            ],
            [
                'name' => 'Şanlıurfa GAP Havalimanı',
                'code' => 'LTCS',
                'latitude' => '37.456667',
                'longitude' => '38.847222',
                'country_id' => 1,
            ],
            [
                'name' => 'Tekirdağ Çorlu Havalimanı',
                'code' => 'LTBU',
                'latitude' => '41.129444',
                'longitude' => '27.906389',
                'country_id' => 1,
            ],
            [
                'name' => 'Trabzon Havalimanı',
                'code' => 'LTCG',
                'latitude' => '40.995278',
                'longitude' => '39.789722',
                'country_id' => 1,
            ],
            [
                'name' => 'Uşak Havalimanı',
                'code' => 'LTBO',
                'latitude' => '38.681389',
                'longitude' => '29.471667',
                'country_id' => 1,
            ],
            [
                'name' => 'Van Ferit Melen Havalimanı',
                'code' => 'LTCI',
                'latitude' => '38.468611',
                'longitude' => '43.3325',
                'country_id' => 1,
            ],
            [
                'name' => 'Zonguldak Havalimanı',
                'code' => 'LTAS',
                'latitude' => '41.506389',
                'longitude' => '32.088611',
                'country_id' => 1,
            ],
            [
                'name' => 'Adıyaman Havalimanı',
                'code' => 'LTCP',
                'latitude' => '37.732222',
                'longitude' => '38.46922015099652',
                'country_id' => 1,
            ],
            [
                'name' => 'Ağrı Ahmed-i Hani Havalimanı',
                'code' => 'LTCO',
                'latitude' => '39.647500',
                'longitude' => '43.028611',
                'country_id' => 1,
            ],
            [
                'name' => 'Amasya Merzifon Havalimanı',
                'code' => 'LTAP',
                'latitude' => '40.829444',
                'longitude' => '35.521667',
                'country_id' => 1,
            ],
            [
                'name' => 'Aydın Çıldır Havalimanı',
                'code' => 'LTBD',
                'latitude' => '37.816111',
                'longitude' => '27.888889',
                'country_id' => 1,
            ],
            [
                'name' => 'Balıkesir Merkez Havalimanı',
                'code' => 'LTBF',
                'latitude' => '39.615556',
                'longitude' => '27.932778',
                'country_id' => 1,
            ],
            [
                'name' => 'Batman Havalimanı',
                'code' => 'LTCJ',
                'latitude' => '37.932222',
                'longitude' => '41.116389',
                'country_id' => 1,
            ],
            [
                'name' => 'Bingöl Havalimanı',
                'code' => 'LTCU',
                'latitude' => '38.861111',
                'longitude' => '40.5925',
                'country_id' => 1,
            ],
            [
                'name' => 'Bursa Yunuseli Havalimanı',
                'code' => 'LTBE',
                'latitude' => '40.233056',
                'longitude' => '29.009167',
                'country_id' => 1,
            ],
            [
                'name' => 'Gökçeada Havalimanı',
                'code' => 'LTFK',
                'latitude' => '40.2',
                'longitude' => '25.881667',
                'country_id' => 1,
            ],
            [
                'name' => 'Erzincan Yıldırım Akbulut Havalimanı',
                'code' => 'LTCD',
                'latitude' => '39.713056',
                'longitude' => '39.520556',
                'country_id' => 1,
            ],
            [
                'name' => 'Sivrihisar Havacılık Merkezi S.H.M.',
                'code' => 'Yok',
                'latitude' => '39.299722',
                'longitude' => '31.494444',
                'country_id' => 1,
            ],
            [
                'name' => 'Hakkâri Yüksekova Selahaddin Eyyubi Havalimanı',
                'code' => 'LTCW',
                'latitude' => '37.549722',
                'longitude' => '44.2375',
                'country_id' => 1,
            ],
            [
                'name' => 'Iğdır Şehit Bülent Aydın Havalimanı',
                'code' => 'LTCT',
                'latitude' => '39.983056',
                'longitude' => '43.866389',
                'country_id' => 1,
            ],
            [
                'name' => 'İstanbul Hezarfen Havalimanı',
                'code' => 'Yok',
                'latitude' => '41.104444',
                'longitude' => '28.55',
                'country_id' => 1,
            ],
            [
                'name' => 'Selçuk-Efes Havalimanı',
                'code' => 'LTFB',
                'latitude' => '37.950556',
                'longitude' => '27.329167',
                'country_id' => 1,
            ],
            [
                'name' => 'Kahramanmaraş Havalimanı',
                'code' => 'LTCN',
                'latitude' => '37.538333',
                'longitude' => '36.951944',
                'country_id' => 1,
            ],
            [
                'name' => 'Kastamonu Havalimanı',
                'code' => 'LTAL',
                'latitude' => '41.316944',
                'longitude' => '33.796111',
                'country_id' => 1,
            ],
            [
                'name' => 'Mardin Prof. Dr. Aziz Sancar Havalimanı',
                'code' => 'LTCR',
                'latitude' => '37.233889',
                'longitude' => '40.640556',
                'country_id' => 1,
            ],
            [
                'name' => 'Muş Havalimanı',
                'code' => 'LTCK',
                'latitude' => '38.744722',
                'longitude' => '41.668889',
                'country_id' => 1,
            ],
            [
                'name' => 'Siirt Havalimanı',
                'code' => 'LTCL',
                'latitude' => '37.978056',
                'longitude' => '41.839167',
                'country_id' => 1,
            ],
            [
                'name' => 'Şırnak Şerafettin Elçi Havalimanı',
                'code' => 'LTCV',
                'latitude' => '37.363889',
                'longitude' => '42.06',
                'country_id' => 1,
            ],
            [
                'name' => 'Tokat Havalimanı',
                'code' => 'LTAW',
                'latitude' => '40.311667',
                'longitude' => '36.373611',
                'country_id' => 1,
            ],
            [
                'name' => 'İncirlik Hava Üssü',
                'code' => 'LTAG',
                'latitude' => '37.001944',
                'longitude' => '35.425833',
                'country_id' => 1,
            ],
            [
                'name' => 'Afyon Havalimanı',
                'code' => 'LTAH',
                'latitude' => '38.726389',
                'longitude' => '30.601111',
                'country_id' => 1,
            ],
            [
                'name' => 'Güvercinlik Havalimanı',
                'code' => 'LTAB',
                'latitude' => '39.934722',
                'longitude' => '32.740556',
                'country_id' => 1,
            ],
            [
                'name' => 'Mürted Hava Üssü',
                'code' => 'LTAE',
                'latitude' => '40.078889',
                'longitude' => '32.565556',
                'country_id' => 1,
            ],
            [
                'name' => 'Etimesgut Havalimanı',
                'code' => 'LTAD',
                'latitude' => '39.949831836202104',
                'longitude' => '32.68888896288863',
                'country_id' => 1,
            ],
            [
                'name' => 'Şanlıurfa GAP Havalimanı',
                'code' => 'GNY',
                'latitude' => '37.1',
                'longitude' => '37.383333',
                'country_id' => 1,
            ],
            [
                'name' => 'Los Angeles',
                'code' => 'LAX',
                'latitude' => '33.942791',
                'longitude' => '-118.410042',
                'country_id' => 2,
            ],
            [
                'name' => 'San Francisco',
                'code' => 'SFO',
                'latitude' => '37.615223',
                'longitude' => '-122.389977',
                'country_id' => 2,
            ],
            [
                'name' => 'Toronto Pearson International Airport',
                'code' => 'YYZ',
                'latitude' => '	43.677128',
                'longitude' => '-79.633453',
                'country_id' => 3,
            ],
            [
                'name' => 'Calgary International Airport',
                'code' => 'YYC',
                'latitude' => '51.121502',
                'longitude' => '-114.007812',
                'country_id' => 3,
            ],
        ];

        foreach ($airports as $index => $airport) {
            Airport::create($airport);
        }
    }
}
